job_id: ar-seg_lora_bce_aia_only_resume
data:
  train_zarr_path: /anvil/scratch/x-jhong6/data/surya_bench_train_hour_8_12.zarr
  valid_zarr_path: /anvil/scratch/x-jhong6/data/surya_bench_validation.zarr
  channels:
  - aia94
  - aia131
  - aia171
  - aia193
  - aia211
  - aia304
  - aia335
  - aia1600
  - hmi_m
  - hmi_bx
  - hmi_by
  - hmi_bz
  - hmi_v
  time_delta_input_minutes:
  - 0
  time_delta_target_minutes: 60
  batch_size: 1
  num_data_workers: 4
  prefetch_factor: 2
  scalers_path: ./assets/scalers.yaml
  ar_index_train:
  - ./assets/ar_index_12min.csv
  ar_index_valid:
  - ./assets/ar_index_12min.csv
  ar_mask_base_dir: ./assets/surya-bench-ar-segmentation
  train_year_start: 2011
  train_year_end: 2017
  daily_only: true
model:
  model_type: spectformer_lora
  img_size: 4096
  patch_size: 16
  in_channels: 13
  time_embedding:
    type: linear
    n_queries: null
    time_dim: 1
  embed_dim: 1280
  depth: 10
  spectral_blocks: 2
  num_heads: 16
  mlp_ratio: 4.0
  rpe: false
  drop_rate: 0.0
  window_size: 2
  dp_rank: 4
  learned_flow: false
  epochs_to_learn_flow: 0
  init_weights: false
  checkpoint_layers: []
  ensemble: null
  unet_embed_dim: 128
  unet_blocks: 3
  finetune: true
  ft_unembedding_type: linear
  ft_out_chans: 1
  use_lora: true
  lora_config:
    r: 32
    lora_alpha: 64
    target_modules:
    - q_proj
    - v_proj
    - k_proj
    - out_proj
    - fc1
    - fc2
    lora_dropout: 0.1
    bias: none
  select: bce
  dice:
    smooth: 1e-5
  iou:
    eps: 1e-6
  bce:
    pos_weight: 1
adapter:
  use_channel_adapter: true
  channels:
  - aia94
  - aia131
  - aia171
  - aia193
  - aia211
  - aia304
  - aia335
  - aia1600
optimizer:
  warm_up_steps: 0
  max_epochs: 25
  learning_rate: 0.0001
  min_lr: 1.0e-06
use_latitude_in_learned_flow: false
loss_weights: []
rollout_steps: 0
num_mask_aia_channels: 0
drop_hmi_probablity: 0.0
validate_after_epoch: 1
wandb_log_train_after: 5
wandb_project: ar-segmentation
visualization_samples: 3
save_wt_after_iter: 100000
path_experiment: checkpoints_aia_only
iters_per_epoch_train: 99999
iters_per_epoch_valid: 99999
iters_grad_accum: 1
dtype: bfloat16
parallelism: ddp
pretrained_path: ./assets/surya.366m.v1.pt
freeze_backbone: false
resume_checkpoint: ./checkpoints_aia_only/epoch_14.pth
start_epoch: 15
